# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=66, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('underlying_asset', models.CharField(max_length=32)),
                ('event_type', models.CharField(choices=[('BINARY', 'Binary'), ('OTHER', 'Other')], default='BINARY', max_length=16)),
                ('status', models.CharField(choices=[('LISTED', 'Listed'), ('TRADING', 'Trading'), ('LOCKED', 'Locked'), ('SETTLING', 'Settling'), ('RESOLVED', 'Resolved'), ('VOIDED', 'Voided'), ('live', 'Live'), ('finalized', 'Finalized')], default='LISTED', max_length=16)),
                ('expiry_time', models.DateTimeField()),
                ('trading_start', models.DateTimeField(blank=True, null=True)),
                ('yes_identifier', models.CharField(max_length=128)),
                ('no_identifier', models.CharField(max_length=128)),
                ('yes_symbol', models.CharField(blank=True, max_length=128)),
                ('no_symbol', models.CharField(blank=True, max_length=128)),
                ('pool_address', models.CharField(blank=True, max_length=66)),
                ('market_address', models.CharField(blank=True, max_length=66)),
                ('venue_id', models.CharField(blank=True, max_length=66)),
                ('strike', models.BigIntegerField(default=0)),
                ('interval_sec', models.PositiveIntegerField(default=900)),
                ('cumulative_quote_volume', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('trade_count', models.PositiveIntegerField(default=0)),
                ('collateral', models.CharField(blank=True, max_length=66)),
                ('oracle_question_id', models.CharField(blank=True, max_length=128)),
                ('winning_outcome', models.CharField(blank=True, max_length=8)),
                ('source', models.CharField(default='dreamdex', max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event contract',
                'verbose_name_plural': 'event contracts',
                'indexes': [models.Index(fields=['external_id'], name='events_even_externa_7249e9_idx'), models.Index(fields=['status'], name='events_even_status_115eb0_idx'), models.Index(fields=['underlying_asset', 'status'], name='events_even_underly_182910_idx'), models.Index(fields=['expiry_time'], name='events_even_expiry__dd6181_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=8)),
                ('external_identifier', models.CharField(max_length=128)),
                ('symbol', models.CharField(blank=True, max_length=128)),
                ('current_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='events.eventcontract')),
            ],
            options={
                'verbose_name': 'event outcome',
                'verbose_name_plural': 'event outcomes',
                'constraints': [models.UniqueConstraint(fields=('event', 'outcome_type'), name='unique_event_outcome_type')],
            },
        ),
        migrations.CreateModel(
            name='EventRadarSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('STRONG_CONSENSUS', 'Strong consensus'), ('MOVING_FAST', 'Moving fast'), ('UNUSUAL_VOLUME', 'Unusual volume'), ('EXPIRING_SOON', 'Expiring soon'), ('TRADER_DIVERGENCE', 'Trader divergence'), ('HIGH_LIQUIDITY', 'High liquidity'), ('PRICE_IMBALANCE', 'Price imbalance')], max_length=64)),
                ('score', models.DecimalField(decimal_places=4, max_digits=8)),
                ('explanation', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_signals', to='events.eventcontract')),
            ],
            options={
                'verbose_name': 'event radar signal',
                'verbose_name_plural': 'event radar signals',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='events_even_event_i_20f98d_idx'), models.Index(fields=['signal_type'], name='events_even_signal__93ad85_idx'), models.Index(fields=['signal_type', 'is_active'], name='events_even_signal__6cfdad_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('no_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('liquidity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('timestamp', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='events.eventcontract')),
            ],
            options={
                'verbose_name': 'event snapshot',
                'verbose_name_plural': 'event snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event', 'timestamp'], name='events_even_event_i_ad8181_idx')],
            },
        ),
    ]
