# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('avatar', models.URLField(blank=True)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('completed_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('total_volume', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('roi', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('trader_score', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
            ],
            options={
                'verbose_name': 'trader profile',
                'verbose_name_plural': 'trader profiles',
                'indexes': [models.Index(fields=['wallet_address'], name='dreamcopy_t_wallet__55c946_idx'), models.Index(fields=['trader_score'], name='dreamcopy_t_trader__13654e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='ACTIVE', max_length=16)),
                ('copy_mode', models.CharField(choices=[('BLIND', 'Blind'), ('SMART', 'Smart'), ('CONSENSUS', 'Consensus')], default='SMART', max_length=16)),
                ('max_per_trade', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('max_daily', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('minimum_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('allowed_assets_json', models.JSONField(blank=True, default=list)),
                ('auto_execute', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_relationships', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_relationships', to='dreamcopy.traderprofile')),
            ],
            options={
                'verbose_name': 'copy relationship',
                'verbose_name_plural': 'copy relationships',
            },
        ),
        migrations.CreateModel(
            name='TraderTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=32)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('external_trade_id', models.CharField(blank=True, max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_trades', to='events.eventcontract')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_trades', to='events.eventoutcome')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='dreamcopy.traderprofile')),
            ],
            options={
                'verbose_name': 'trader trade',
                'verbose_name_plural': 'trader trades',
            },
        ),
        migrations.CreateModel(
            name='CopyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_decision', models.CharField(blank=True, max_length=64)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copied_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_executions', to='trading.trade')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='dreamcopy.copyrelationship')),
                ('source_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_executions', to='dreamcopy.tradertrade')),
            ],
            options={
                'verbose_name': 'copy execution',
                'verbose_name_plural': 'copy executions',
            },
        ),
        migrations.AddIndex(
            model_name='copyrelationship',
            index=models.Index(fields=['user', 'status'], name='dreamcopy_c_user_id_4a9ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrelationship',
            index=models.Index(fields=['status'], name='dreamcopy_c_status_847910_idx'),
        ),
        migrations.AddConstraint(
            model_name='copyrelationship',
            constraint=models.UniqueConstraint(fields=('user', 'trader'), name='unique_user_trader_copy'),
        ),
        migrations.AddIndex(
            model_name='tradertrade',
            index=models.Index(fields=['trader', 'opened_at'], name='dreamcopy_t_trader__45ee47_idx'),
        ),
        migrations.AddIndex(
            model_name='tradertrade',
            index=models.Index(fields=['external_trade_id'], name='dreamcopy_t_externa_5c8bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='tradertrade',
            index=models.Index(fields=['transaction_hash'], name='dreamcopy_t_transac_c5507a_idx'),
        ),
        migrations.AddIndex(
            model_name='copyexecution',
            index=models.Index(fields=['status'], name='dreamcopy_c_status_449c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='copyexecution',
            index=models.Index(fields=['relationship', 'created_at'], name='dreamcopy_c_relatio_7f0df1_idx'),
        ),
        migrations.AddConstraint(
            model_name='copyexecution',
            constraint=models.UniqueConstraint(fields=('relationship', 'source_trade'), name='unique_copy_execution_per_source_trade'),
        ),
    ]
