# Generated by Django 5.x for Smart Copy fields

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreamcopy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="copyrelationship",
            name="min_copy_score",
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name="copyrelationship",
            name="min_win_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.65"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="copyrelationship",
            name="min_completed_events",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="copyrelationship",
            name="min_liquidity",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("1000"), max_digits=24
            ),
        ),
        migrations.AddField(
            model_name="copyrelationship",
            name="min_consensus",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.60"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="copyrelationship",
            name="consider_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flags: trader_confidence, historical_performance, liquidity, "
                "market_movement, consensus, copy_every",
            ),
        ),
        migrations.AddField(
            model_name="copyexecution",
            name="copy_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="copyexecution",
            name="score_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="copyexecution",
            name="why_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="copyexecution",
            name="risks_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="copyexecution",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Notional size that would be / was copied.",
                max_digits=24,
                null=True,
            ),
        ),
    ]
