# Generated by Django 5.2.17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACTIVE", "Active")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("confirm_token", models.CharField(blank=True, max_length=64)),
                ("confirm_expires_at", models.DateTimeField(blank=True, null=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_link",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "telegram link",
                "verbose_name_plural": "telegram links",
                "indexes": [
                    models.Index(
                        fields=["chat_id", "status"],
                        name="accounts_te_chat_id_8c3e1a_idx",
                    )
                ],
            },
        ),
    ]
