# Generated by Django 5.2.17 on 2026-08-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telegramlink',
            new_name='accounts_te_chat_id_809a79_idx',
            old_name='accounts_te_chat_id_8c3e1a_idx',
        ),
    ]
