# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('liquidity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_activity', to='events.eventcontract')),
            ],
            options={
                'verbose_name': 'market activity',
                'verbose_name_plural': 'market activities',
            },
        ),
    ]
