# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('external_trade_id', models.CharField(blank=True, max_length=128)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('status', models.CharField(choices=[('PREPARED', 'Prepared'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PREPARED', max_length=32)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=32)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='events.eventcontract')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='events.eventoutcome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trades',
                'indexes': [models.Index(fields=['status'], name='trading_tra_status_252e0c_idx'), models.Index(fields=['external_trade_id'], name='trading_tra_externa_c97832_idx'), models.Index(fields=['transaction_hash'], name='trading_tra_transac_ce1f7b_idx'), models.Index(fields=['user', 'status'], name='trading_tra_user_id_d8b231_idx')],
            },
        ),
    ]
