# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('rpc_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'network config',
                'verbose_name_plural': 'network configs',
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('receipt_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction record',
                'verbose_name_plural': 'transaction records',
                'indexes': [models.Index(fields=['status'], name='blockchain__status_8fc0fe_idx'), models.Index(fields=['user', 'status'], name='blockchain__user_id_c0e30d_idx')],
            },
        ),
    ]
