# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent session',
                'verbose_name_plural': 'agent sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agentsession')),
            ],
            options={
                'verbose_name': 'agent message',
                'verbose_name_plural': 'agent messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=128)),
                ('arguments_json', models.JSONField(default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='agents.agentmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agents.agentsession')),
            ],
            options={
                'verbose_name': 'agent tool call',
                'verbose_name_plural': 'agent tool calls',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=6)),
                ('reasoning', models.TextField()),
                ('structured_output_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to='events.eventcontract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent decision',
                'verbose_name_plural': 'agent decisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='agents_agen_user_id_39dacf_idx'), models.Index(fields=['event', 'created_at'], name='agents_agen_event_i_b7843c_idx')],
            },
        ),
    ]
