# Generated by Django 5.2.17 on 2026-08-24 13:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('dreamcopy', '0002_smart_copy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DreamAgent', max_length=128)),
                ('session_address', models.CharField(help_text='Public address of the session EOA delegate (never stores private keys here).', max_length=42)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('FUNDED', 'Funded'), ('CONFIGURED', 'Configured'), ('AUTHORIZED', 'Authorized'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='CREATED', max_length=16)),
                ('initial_capital', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dream agent',
                'verbose_name_plural': 'dream agents',
            },
        ),
        migrations.CreateModel(
            name='SmartAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_address', models.CharField(max_length=42)),
                ('address', models.CharField(max_length=42)),
                ('chain_id', models.PositiveIntegerField()),
                ('factory_address', models.CharField(blank=True, max_length=42)),
                ('deploy_salt', models.CharField(default='0x', max_length=66)),
                ('implementation', models.CharField(default='Hybrid', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPLOYED', 'Deployed'), ('FUNDED', 'Funded')], default='PENDING', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'smart account',
                'verbose_name_plural': 'smart accounts',
            },
        ),
        migrations.CreateModel(
            name='DreamAgentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_address', models.CharField(max_length=42)),
                ('chain_id', models.PositiveIntegerField()),
                ('permission_type', models.CharField(choices=[('TRADE_EVENT_CONTRACT', 'Trade Event Contract')], default='TRADE_EVENT_CONTRACT', max_length=32)),
                ('max_trade_amount', models.DecimalField(decimal_places=8, default=Decimal('10'), max_digits=24)),
                ('max_daily_volume', models.DecimalField(decimal_places=8, default=Decimal('50'), max_digits=24)),
                ('min_copy_score', models.PositiveIntegerField(default=75)),
                ('allowed_traders_json', models.JSONField(blank=True, default=list, help_text='TraderProfile IDs or wallet addresses the agent may copy.')),
                ('allowed_outcomes_json', models.JSONField(blank=True, default=list)),
                ('allowed_contracts_json', models.JSONField(blank=True, default=list, help_text='DreamDEX pool addresses allowed as delegation targets.')),
                ('caveats_json', models.JSONField(blank=True, default=dict)),
                ('signed_delegation_json', models.JSONField(blank=True, default=dict, help_text='Signed ERC-7710 delegation blob for redeemDelegations.')),
                ('delegation_hash', models.CharField(blank=True, max_length=66)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='agents.dreamagent')),
                ('smart_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='agents.smartaccount')),
            ],
            options={
                'verbose_name': 'dream agent permission',
                'verbose_name_plural': 'dream agent permissions',
            },
        ),
        migrations.AddField(
            model_name='dreamagent',
            name='smart_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agents.smartaccount'),
        ),
        migrations.CreateModel(
            name='AgentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('COPY', 'Copy'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=16)),
                ('copy_score', models.PositiveIntegerField(blank=True, null=True)),
                ('trader_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('event_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('consensus_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('skip_reasons_json', models.JSONField(blank=True, default=list)),
                ('policy_json', models.JSONField(blank=True, default=dict)),
                ('risk_json', models.JSONField(blank=True, default=dict)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('event_title', models.CharField(blank=True, max_length=256)),
                ('outcome', models.CharField(blank=True, max_length=16)),
                ('trader_name', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_evaluations', to='dreamcopy.copyexecution')),
                ('source_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_evaluations', to='dreamcopy.tradertrade')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='agents.dreamagent')),
            ],
            options={
                'verbose_name': 'agent evaluation',
                'verbose_name_plural': 'agent evaluations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_c054c2_idx'), models.Index(fields=['agent', 'decision'], name='agents_agen_agent_i_5757ce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='smartaccount',
            index=models.Index(fields=['user', 'chain_id'], name='agents_smar_user_id_846bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='smartaccount',
            index=models.Index(fields=['address'], name='agents_smar_address_3629a3_idx'),
        ),
        migrations.AddIndex(
            model_name='smartaccount',
            index=models.Index(fields=['owner_address'], name='agents_smar_owner_a_b9144d_idx'),
        ),
        migrations.AddConstraint(
            model_name='smartaccount',
            constraint=models.UniqueConstraint(fields=('user', 'chain_id'), name='unique_user_smart_account_chain'),
        ),
        migrations.AddConstraint(
            model_name='smartaccount',
            constraint=models.UniqueConstraint(fields=('address', 'chain_id'), name='unique_smart_account_address_chain'),
        ),
        migrations.AddIndex(
            model_name='dreamagentpermission',
            index=models.Index(fields=['agent', 'status'], name='agents_drea_agent_i_d1a5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='dreamagentpermission',
            index=models.Index(fields=['status', 'expires_at'], name='agents_drea_status_bcfe81_idx'),
        ),
        migrations.AddIndex(
            model_name='dreamagent',
            index=models.Index(fields=['user', 'status'], name='agents_drea_user_id_d8dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='dreamagent',
            index=models.Index(fields=['session_address'], name='agents_drea_session_7f674b_idx'),
        ),
    ]
