# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_consensus', models.DecimalField(decimal_places=8, max_digits=18)),
                ('no_consensus', models.DecimalField(decimal_places=8, max_digits=18)),
                ('trader_count', models.PositiveIntegerField(default=0)),
                ('agreement_level', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_snapshots', to='events.eventcontract')),
            ],
            options={
                'verbose_name': 'consensus snapshot',
                'verbose_name_plural': 'consensus snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='analytics_c_event_i_edfebc_idx')],
            },
        ),
    ]
