# Generated by Django 5.2.17 on 2026-08-22 23:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('current_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SETTLED', 'Settled')], default='OPEN', max_length=16)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='events.eventcontract')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='events.eventoutcome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'indexes': [models.Index(fields=['user', 'status'], name='portfolio_p_user_id_bafcad_idx'), models.Index(fields=['status'], name='portfolio_p_status_1518fe_idx')],
            },
        ),
    ]
